// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEjgzEVO-Q3RMQCuRkdiMmY2FKldxnyB0',
    appId: '1:950583156912:web:084ece6ba5f8225e16db75',
    messagingSenderId: '950583156912',
    projectId: 'guardly-3f876',
    authDomain: 'guardly-3f876.firebaseapp.com',
    storageBucket: 'guardly-3f876.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk2I_T-eEoZWQv6Yayye-U-EjyQpf8vTk',
    appId: '1:950583156912:android:829f0c7a0825c4b516db75',
    messagingSenderId: '950583156912',
    projectId: 'guardly-3f876',
    storageBucket: 'guardly-3f876.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW8q2S3ZtjvBmQTf4bSTaykB_l32kZCqw',
    appId: '1:950583156912:ios:e4f8d9fd990e54aa16db75',
    messagingSenderId: '950583156912',
    projectId: 'guardly-3f876',
    storageBucket: 'guardly-3f876.firebasestorage.app',
    iosBundleId: 'com.example.mindshield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW8q2S3ZtjvBmQTf4bSTaykB_l32kZCqw',
    appId: '1:950583156912:ios:e4f8d9fd990e54aa16db75',
    messagingSenderId: '950583156912',
    projectId: 'guardly-3f876',
    storageBucket: 'guardly-3f876.firebasestorage.app',
    iosBundleId: 'com.example.mindshield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEjgzEVO-Q3RMQCuRkdiMmY2FKldxnyB0',
    appId: '1:950583156912:web:8bebe22fbc1f035916db75',
    messagingSenderId: '950583156912',
    projectId: 'guardly-3f876',
    authDomain: 'guardly-3f876.firebaseapp.com',
    storageBucket: 'guardly-3f876.firebasestorage.app',
  );
}
